name: ServerModeration
version: ${project.version}
main: com.github.carthax08.servermoderation.Main
authors: [CarThax08]
description: Adds moderation features to Minecraft Servers on top of what Spigot already offers.
website: github.com/CarThax08
commands:
  tempban:
    description: Temporarily Bans a Player
    usage: /tempban [player] [time] [s,min,h,d] [reason]
  ban:
    description: Bans a player permanantley
    usage: /ban [player] [reason]
  unban:
    descripiton: Unbans a player
    usage: /unban [player]
  unbanip:
    description: Unbans an IP
    usage: /unbanip [ip]
  banip:
    description: Bans and IP
    usage: /banip [ip/player]
